/**
 * backend/scripts/seedReadingBand80Plus.js
 *
 * Seeds 7 band_80_plus reading passages (neuroscience, critical_theory,
 * economics, science) + questions.
 * Uses a transaction for atomicity. Idempotent — skips existing passages by title.
 *
 * Usage (from backend/ directory):
 *   node scripts/seedReadingBand80Plus.js
 */

"use strict";

const path = require("path");
const crypto = require("crypto");

const BACKEND_DIR = path.resolve(__dirname, "..");
require("dotenv").config({ path: path.join(BACKEND_DIR, ".env"), override: false });

const { pool } = require(path.join(BACKEND_DIR, "src", "config", "db.js"));

function makeUUID(key) {
  const hash = crypto.createHash("md5").update(key).digest("hex");
  return [hash.slice(0,8), hash.slice(8,12), hash.slice(12,16), hash.slice(16,20), hash.slice(20,32)].join("-");
}

const PASSAGES = [
  {
    id: makeUUID("band80-neuro-neuroplasticity"),
    topic: "neuroscience", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Neuroplasticity and the Architecture of Constraint",
    passage_text: "A. Neuroplasticity has long been celebrated as the neural substrate of learning and adaptation, often portrayed in popular discourse as evidence of the brain\u2019s near-limitless capacity for self-reinvention. However, this characterization obscures a more intricate reality: plasticity is not an unbounded phenomenon but one that is tightly regulated by both structural and functional constraints. These constraints are not merely incidental but are integral to maintaining the stability of cognitive systems, preventing the destabilization that would arise from indiscriminate neural reconfiguration.\n\nB. Contemporary research distinguishes between multiple forms of plasticity, most notably synaptic plasticity, which involves the modulation of connection strength, and large-scale reorganization, which entails shifts in cortical representation. Crucially, the brain exhibits a marked preference for the former, as it allows for efficient recalibration without the metabolic and computational costs associated with structural overhaul. This prioritization suggests that the brain operates according to an economy of change, wherein adaptability is balanced against the preservation of established functional architectures.\n\nC. Furthermore, neuroplasticity is frequently characterized by selective inhibition rather than generative expansion. Learning, in many contexts, involves the attenuation of competing neural pathways, thereby enhancing the signal-to-noise ratio within relevant circuits. This process is particularly evident during developmental critical periods, where synaptic pruning refines neural networks by eliminating redundant connections. Importantly, such pruning does not signify loss but rather optimization, enabling more precise and efficient information processing.\n\nD. The persistence of plasticity into adulthood has been widely documented, yet it is increasingly understood as contingent upon a constellation of factors, including neuromodulatory states, environmental variability, and prior experiential history. Rather than a uniform capacity, adult plasticity is unevenly distributed and often constrained by entrenched neural patterns. Consequently, the notion of lifelong, unrestricted adaptability must be reconsidered in favor of a model that emphasizes context-dependent modulation. In this view, neuroplasticity emerges not as a boundless resource but as a carefully calibrated mechanism, mediating the tension between flexibility and stability within the brain\u2019s dynamic architecture.",
    tags: ["neuroscience"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the primary argument presented in the passage?", options: { A: "Neuroplasticity enables unlimited neural reorganization throughout life", B: "Neuroplasticity is a constrained and regulated process balancing change and stability", C: "Structural brain changes are more significant than functional changes", D: "Neuroplasticity is only relevant during early development" }, correct_answer: "B", explanation: "The passage consistently emphasizes constraints and regulation." },
      { order_index: 2, type: "mcq", question_text: "Why does the brain favor synaptic plasticity over large-scale reorganization?", options: { A: "It is more visible in experimental settings", B: "It eliminates the need for structural changes entirely", C: "It minimizes metabolic and computational costs", D: "It occurs only during early development" }, correct_answer: "C", explanation: "Paragraph B states it avoids high costs of structural changes." },
      { order_index: 3, type: "mcq", question_text: "What role does synaptic pruning play in neural development?", options: { A: "It reduces overall brain capacity", B: "It eliminates essential neural pathways", C: "It optimizes neural networks by removing redundant connections", D: "It prevents further learning in adulthood" }, correct_answer: "C", explanation: "Paragraph C explains pruning enhances efficiency." },
      { order_index: 4, type: "tfng", question_text: "Neuroplasticity operates without limitations in all stages of life.", options: null, correct_answer: "FALSE", explanation: "The passage explicitly states it is constrained." },
      { order_index: 5, type: "tfng", question_text: "Large-scale cortical reorganization is the brain's primary mechanism for adaptation.", options: null, correct_answer: "FALSE", explanation: "Paragraph B indicates the brain prefers synaptic plasticity." },
      { order_index: 6, type: "tfng", question_text: "The passage states that all individuals experience the same degree of neuroplasticity in adulthood.", options: null, correct_answer: "NOT GIVEN", explanation: "Variability is mentioned but individuals are not compared." },
      { order_index: 7, type: "matching", question_text: "Match paragraph B with its main idea", options: { A: "The cost-efficiency of different forms of plasticity", B: "The developmental role of pruning", C: "The limits of adult plasticity", D: "The philosophical implications of plasticity" }, correct_answer: "A", explanation: "Paragraph B focuses on efficiency and cost." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Mechanisms of synaptic inhibition", B: "Context-dependent nature of adult neuroplasticity", C: "Early developmental processes", D: "Experimental methods in neuroscience" }, correct_answer: "B", explanation: "Paragraph D discusses adult plasticity and context." },
    ],
  },
  {
    id: makeUUID("band80-neuro-consciousness"),
    topic: "neuroscience", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Competing Architectures of Consciousness",
    passage_text: "A. The scientific study of consciousness has long been characterized by a tension between reductive and integrative frameworks. While early neurobiological accounts sought to localize consciousness within discrete brain regions, contemporary theories increasingly conceptualize it as an emergent property of distributed neural processes. This shift reflects growing recognition that subjective experience cannot be straightforwardly mapped onto isolated anatomical structures, but instead arises from dynamic interactions across large-scale networks.\n\nB. Among the most influential models is the Global Workspace Theory (GWT), which posits that consciousness emerges when information is globally broadcast across a network of specialized processors. According to this view, unconscious processes operate in parallel and compete for access to a limited-capacity workspace. Once information gains access, it becomes widely available for reasoning, decision-making, and verbal report. Critics, however, argue that GWT prioritizes functional accessibility over phenomenological richness, thereby neglecting the qualitative dimensions of experience.\n\nC. In contrast, Integrated Information Theory (IIT) approaches consciousness from a fundamentally different angle, proposing that it corresponds to the system\u2019s capacity to integrate information. Rather than focusing on functional roles, IIT attempts to quantify consciousness through a measure known as phi, representing the degree of irreducible informational unity. While theoretically ambitious, IIT has been criticized for its abstract formalism and for attributing rudimentary forms of consciousness to systems that lack any plausible subjective experience.\n\nD. These competing frameworks illustrate a deeper epistemological divide within consciousness research. Whereas GWT aligns with a computational and functionally oriented paradigm, IIT reflects a more ontologically driven approach concerned with the intrinsic nature of experience. Neither theory has achieved definitive empirical validation, and both face significant methodological challenges. Consequently, the study of consciousness remains an open field, marked not by consensus but by productive theoretical pluralism, in which divergent models continue to illuminate different facets of one of science\u2019s most elusive phenomena.",
    tags: ["neuroscience"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the main focus of the passage?", options: { A: "To prove that one theory of consciousness is correct", B: "To compare competing theories and highlight their differences", C: "To explain how consciousness is localized in the brain", D: "To reject all existing theories of consciousness" }, correct_answer: "B", explanation: "The passage contrasts GWT and IIT." },
      { order_index: 2, type: "mcq", question_text: "According to Global Workspace Theory, what characterizes conscious information?", options: { A: "It is stored permanently in memory", B: "It is processed only in isolated brain regions", C: "It is broadcast across multiple cognitive systems", D: "It is independent of neural activity" }, correct_answer: "C", explanation: "GWT describes consciousness as globally broadcast." },
      { order_index: 3, type: "mcq", question_text: "What is a major criticism of Integrated Information Theory?", options: { A: "It ignores neural processes entirely", B: "It is too focused on functional accessibility", C: "It attributes consciousness too broadly based on abstract measures", D: "It cannot explain unconscious processing" }, correct_answer: "C", explanation: "Paragraph C notes IIT assigns consciousness to unlikely systems." },
      { order_index: 4, type: "tfng", question_text: "Early theories of consciousness primarily focused on distributed neural networks.", options: null, correct_answer: "FALSE", explanation: "Paragraph A states early theories focused on localized regions." },
      { order_index: 5, type: "tfng", question_text: "Global Workspace Theory fully explains the qualitative nature of subjective experience.", options: null, correct_answer: "FALSE", explanation: "It is criticized for neglecting phenomenological richness." },
      { order_index: 6, type: "tfng", question_text: "Both GWT and IIT have been conclusively validated by empirical research.", options: null, correct_answer: "FALSE", explanation: "Paragraph D states neither has definitive validation." },
      { order_index: 7, type: "matching", question_text: "Match paragraph B with its main idea", options: { A: "Critique of theoretical pluralism", B: "Explanation and limitations of Global Workspace Theory", C: "Introduction to consciousness research", D: "Philosophical implications of IIT" }, correct_answer: "B", explanation: "Paragraph B outlines GWT and its criticism." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Epistemological divide and lack of consensus", B: "Detailed explanation of IIT", C: "Neural mechanisms of consciousness", D: "Historical overview" }, correct_answer: "A", explanation: "Paragraph D highlights the broader divide." },
    ],
  },
  {
    id: makeUUID("band80-neuro-decision-choice"),
    topic: "neuroscience", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Neural Economies of Choice",
    passage_text: "A. Decision neuroscience seeks to elucidate how the brain evaluates alternatives and selects among them, yet its findings have complicated rather than simplified classical models of rational choice. Traditional economic theory presumes that agents compute expected utilities in a consistent and internally coherent manner. However, neural evidence suggests that valuation is neither unitary nor stable; instead, it is constructed dynamically through the interaction of multiple, often competing, neural systems.\n\nB. Central to this framework is the distinction between model-based and model-free systems. The former engages in prospective simulation, drawing upon stored representations to anticipate future outcomes, while the latter relies on cached values derived from prior reinforcement. Neuroimaging studies implicate prefrontal regions in model-based processing and subcortical structures, such as the striatum, in model-free learning. Crucially, these systems do not operate in isolation but interact in ways that can produce both adaptive flexibility and systematic bias.\n\nC. The integration of affective and cognitive signals further complicates the decision-making process. Regions such as the ventromedial prefrontal cortex appear to encode subjective value by integrating emotional salience with abstract considerations. Yet this integration is susceptible to contextual modulation: framing effects, temporal discounting, and social influences can all recalibrate perceived value without altering underlying outcomes. Such findings challenge the assumption that preferences are stable, instead suggesting that they are constructed in situ.\n\nD. These insights have prompted a reconceptualization of rationality itself. Rather than viewing deviations from normative models as errors, some researchers argue that they reflect the brain\u2019s optimization under constraints, including limited computational resources and environmental uncertainty. From this perspective, so-called biases may represent heuristics that are locally adaptive, even if they produce globally inconsistent behavior. Decision neuroscience thus reframes rationality as an emergent property of bounded systems, navigating trade-offs between accuracy, efficiency, and adaptability.",
    tags: ["neuroscience"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the central claim of the passage?", options: { A: "Human decision-making strictly follows rational economic models", B: "Neural processes reveal decision-making as dynamic and multi-systemic", C: "Only emotional factors influence decisions", D: "Model-free systems dominate all forms of decision-making" }, correct_answer: "B", explanation: "The passage emphasizes multiple interacting neural systems." },
      { order_index: 2, type: "mcq", question_text: "What distinguishes model-based from model-free systems?", options: { A: "Model-based relies on past rewards, while model-free simulates the future", B: "Model-based simulates future outcomes, while model-free uses stored values", C: "Model-based operates unconsciously, while model-free is conscious", D: "Model-based is emotional, while model-free is rational" }, correct_answer: "B", explanation: "Paragraph B clearly defines the distinction." },
      { order_index: 3, type: "mcq", question_text: "Why are preferences described as 'constructed in situ'?", options: { A: "They are fixed from birth", B: "They are determined solely by genetics", C: "They are shaped by context and situational factors", D: "They are irrelevant to decision-making" }, correct_answer: "C", explanation: "Paragraph C explains contextual influences." },
      { order_index: 4, type: "tfng", question_text: "Traditional economic theory assumes stable and consistent preferences.", options: null, correct_answer: "TRUE", explanation: "Paragraph A contrasts neural findings with this assumption." },
      { order_index: 5, type: "tfng", question_text: "Model-based and model-free systems function independently without interaction.", options: null, correct_answer: "FALSE", explanation: "Paragraph B states they interact." },
      { order_index: 6, type: "tfng", question_text: "All researchers agree that biases are purely irrational errors.", options: null, correct_answer: "FALSE", explanation: "Paragraph D suggests biases can be adaptive heuristics." },
      { order_index: 7, type: "matching", question_text: "Match paragraph C with its main idea", options: { A: "Interaction of decision systems", B: "Context-dependent construction of value", C: "Definition of rationality", D: "Historical overview of economics" }, correct_answer: "B", explanation: "Paragraph C focuses on contextual influences on value." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Critique of neural imaging", B: "Reconceptualization of rationality under constraints", C: "Biological basis of emotions", D: "Types of neural systems" }, correct_answer: "B", explanation: "Paragraph D redefines rationality." },
    ],
  },
  {
    id: makeUUID("band80-crit-postcolonialism"),
    topic: "critical_theory", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Postcolonialism and the Persistence of Epistemic Hierarchies",
    passage_text: "A. Postcolonial theory interrogates not only the historical realities of imperial domination but also the enduring epistemic frameworks through which such domination continues to operate. While formal colonial rule has largely receded, its intellectual and cultural residues persist in the privileging of Western modes of knowledge production. These hierarchies are neither incidental nor easily dismantled; they are embedded in institutional practices, disciplinary canons, and the ostensibly neutral standards by which knowledge is evaluated.\n\nB. Central to this critique is the concept of epistemic violence, which denotes the systematic marginalization or erasure of subaltern voices. Rather than overt suppression, this violence often manifests through subtler mechanisms, such as the translation of non-Western knowledge into Western categories that distort or dilute its meaning. In this process, alternative epistemologies are not simply excluded but are reconfigured in ways that render them legible only within dominant paradigms.\n\nC. The notion of hybridity has been proposed as a counterpoint to such rigid binaries, emphasizing the fluid and negotiated nature of cultural identity in postcolonial contexts. However, this concept is not without its critics. Some argue that the celebration of hybridity risks obscuring ongoing power asymmetries, presenting cultural mixing as a neutral or even emancipatory process while neglecting the structural inequalities that shape it. Thus, hybridity may inadvertently reproduce the very hierarchies it seeks to destabilize.\n\nD. These tensions underscore a broader challenge within postcolonial thought: how to articulate forms of resistance that do not merely invert existing hierarchies but fundamentally reconfigure the conditions of knowledge production. This entails not only recovering marginalized perspectives but also questioning the criteria by which knowledge is legitimized. In doing so, postcolonial theory moves beyond critique toward the possibility of epistemic pluralism, wherein multiple ways of knowing coexist without being subsumed under a singular, dominant framework.",
    tags: ["critical_theory"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the primary focus of postcolonial theory in the passage?", options: { A: "The economic consequences of colonialism", B: "The persistence of knowledge hierarchies after colonialism", C: "The complete disappearance of colonial influence", D: "The superiority of Western epistemology" }, correct_answer: "B", explanation: "Paragraph A emphasizes enduring epistemic frameworks." },
      { order_index: 2, type: "mcq", question_text: "What does 'epistemic violence' refer to in this context?", options: { A: "Physical suppression of colonized populations", B: "Direct censorship of all non-Western ideas", C: "Subtle distortion and marginalization of alternative knowledge systems", D: "Violent conflicts between cultures" }, correct_answer: "C", explanation: "Paragraph B explains epistemic violence as subtle distortion." },
      { order_index: 3, type: "mcq", question_text: "Why is the concept of hybridity criticized?", options: { A: "It denies cultural interaction", B: "It ignores historical colonialism entirely", C: "It may conceal ongoing power inequalities", D: "It rejects all forms of identity" }, correct_answer: "C", explanation: "Paragraph C notes hybridity can obscure structural inequalities." },
      { order_index: 4, type: "tfng", question_text: "Postcolonial theory argues that colonial influence has completely ended.", options: null, correct_answer: "FALSE", explanation: "The passage states colonial residues persist." },
      { order_index: 5, type: "tfng", question_text: "Epistemic violence always involves explicit and visible suppression.", options: null, correct_answer: "FALSE", explanation: "Paragraph B emphasizes subtle mechanisms." },
      { order_index: 6, type: "tfng", question_text: "The passage provides a detailed method for achieving epistemic pluralism.", options: null, correct_answer: "NOT GIVEN", explanation: "It discusses the idea but not a detailed method." },
      { order_index: 7, type: "matching", question_text: "Match paragraph B with its main idea", options: { A: "Critique of hybridity", B: "Explanation of epistemic violence", C: "Historical colonial rule", D: "Future of knowledge systems" }, correct_answer: "B", explanation: "Paragraph B defines epistemic violence." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Call for epistemic transformation and pluralism", B: "Definition of hybridity", C: "Colonial history", D: "Language translation issues" }, correct_answer: "A", explanation: "Paragraph D discusses reconfiguring knowledge systems." },
    ],
  },
  {
    id: makeUUID("band80-crit-algorithmic-media"),
    topic: "critical_theory", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Algorithmic Mediation and the Fragmentation of Public Discourse",
    passage_text: "A. Media theory has increasingly shifted its analytical focus from content to infrastructure, emphasizing how the architectures of communication systems shape the production and circulation of meaning. In contemporary digital environments, platforms do not merely host discourse but actively curate and modulate it through algorithmic processes. These processes operate according to proprietary logics that are often opaque, thereby complicating traditional notions of authorship, agency, and audience.\n\nB. Central to this transformation is the rise of algorithmic personalization, which selectively filters information based on user behavior and inferred preferences. While frequently justified in terms of relevance and efficiency, such filtering mechanisms can produce epistemic enclaves in which individuals are disproportionately exposed to confirmatory perspectives. This phenomenon, often described as the formation of echo chambers, challenges the ideal of a shared public sphere in which diverse viewpoints are collectively negotiated.\n\nC. However, the explanatory power of the echo chamber metaphor has been contested. Critics argue that it oversimplifies the dynamics of digital discourse by neglecting the role of platform design, economic incentives, and user heterogeneity. Rather than isolated informational bubbles, online environments may be better understood as sites of algorithmically amplified contestation, where visibility is unevenly distributed and certain forms of engagement are systematically privileged over others.\n\nD. These developments necessitate a reconsideration of media power in the digital age. Power is no longer exercised solely through the control of content but through the modulation of attention and the structuring of informational pathways. Consequently, critical analysis must extend beyond representational critique to encompass the technical and economic conditions that govern visibility. In doing so, media theory seeks to illuminate the subtle yet pervasive mechanisms through which contemporary communication systems shape not only what is seen, but what can be thought.",
    tags: ["critical_theory"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the main argument of the passage?", options: { A: "Digital media platforms simply transmit user-generated content", B: "Media theory should ignore technological infrastructure", C: "Algorithmic systems actively shape and structure public discourse", D: "Echo chambers fully explain all online communication patterns" }, correct_answer: "C", explanation: "The passage emphasizes the active role of algorithms." },
      { order_index: 2, type: "mcq", question_text: "Why is algorithmic personalization significant?", options: { A: "It eliminates bias in information distribution", B: "It ensures all users see identical content", C: "It filters content based on user behavior, potentially limiting perspectives", D: "It prevents any form of misinformation" }, correct_answer: "C", explanation: "Paragraph B explains filtering and its consequences." },
      { order_index: 3, type: "mcq", question_text: "What criticism is made of the 'echo chamber' concept?", options: { A: "It exaggerates the role of users", B: "It fails to account for structural and economic factors", C: "It ignores all forms of algorithmic influence", D: "It suggests platforms are neutral" }, correct_answer: "B", explanation: "Paragraph C notes it oversimplifies and ignores platform design." },
      { order_index: 4, type: "tfng", question_text: "The passage suggests that digital platforms are neutral intermediaries.", options: null, correct_answer: "FALSE", explanation: "Paragraph A states platforms actively curate discourse." },
      { order_index: 5, type: "tfng", question_text: "Algorithmic personalization always leads to a more diverse range of viewpoints.", options: null, correct_answer: "FALSE", explanation: "Paragraph B indicates it can limit exposure to diverse views." },
      { order_index: 6, type: "tfng", question_text: "The passage claims that economic incentives have no role in shaping digital discourse.", options: null, correct_answer: "FALSE", explanation: "Paragraph C explicitly mentions economic incentives." },
      { order_index: 7, type: "matching", question_text: "Match paragraph B with its main idea", options: { A: "Critique of media infrastructure", B: "Effects of algorithmic personalization on information exposure", C: "Historical development of media theory", D: "Technical design of algorithms" }, correct_answer: "B", explanation: "Paragraph B discusses filtering and echo chambers." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Reconceptualization of media power and visibility", B: "Definition of echo chambers", C: "User behavior analysis", D: "Critique of algorithms" }, correct_answer: "A", explanation: "Paragraph D focuses on redefining media power." },
    ],
  },
  {
    id: makeUUID("band80-econ-monetary-theory"),
    topic: "economics", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Monetary Sovereignty and the Limits of Policy Transmission",
    passage_text: "A. Monetary theory has undergone significant transformation in response to persistent anomalies in macroeconomic behavior, particularly in low-inflation, low-interest-rate environments. Traditional frameworks, grounded in the quantity theory of money, posit a relatively stable relationship between money supply and price levels. Yet empirical evidence from advanced economies has increasingly undermined this assumption, revealing a more complex and contingent relationship mediated by institutional structures and behavioral expectations.\n\nB. Central to contemporary debates is the concept of monetary sovereignty, which refers to a state\u2019s capacity to issue its own currency and conduct independent monetary policy. Proponents argue that such sovereignty affords governments greater fiscal flexibility, enabling them to finance expenditures without immediate recourse to taxation or external borrowing. However, critics caution that this perspective underestimates the constraints imposed by inflationary pressures, exchange rate volatility, and the credibility of monetary institutions.\n\nC. The transmission mechanisms through which monetary policy affects the real economy further complicate the picture. Conventional models emphasize interest rate adjustments as the primary conduit, influencing investment and consumption decisions. However, in conditions where interest rates approach the zero lower bound, these mechanisms become attenuated. In such contexts, alternative channels such as expectations management and unconventional policies like quantitative easing assume greater significance, though their efficacy remains contested and uneven across different economic settings.\n\nD. These developments have prompted a reevaluation of the role of central banks and the theoretical foundations that underpin their actions. Rather than operating as neutral arbiters of economic stability, central banks are increasingly recognized as embedded within broader political and institutional frameworks. Consequently, monetary policy cannot be fully understood in isolation from fiscal dynamics, global capital flows, and the distributional effects of policy interventions. The evolving landscape of monetary theory thus reflects a shift toward a more integrated and context-sensitive understanding of economic governance.",
    tags: ["economics"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the main argument of the passage?", options: { A: "Traditional monetary theory fully explains modern economic conditions", B: "Monetary relationships are more complex and context-dependent than previously assumed", C: "Interest rates are always effective in controlling inflation", D: "Central banks operate independently of political systems" }, correct_answer: "B", explanation: "The passage emphasizes complexity and challenges to traditional theory." },
      { order_index: 2, type: "mcq", question_text: "What is meant by 'monetary sovereignty'?", options: { A: "The ability to control global financial markets", B: "The power to regulate private banks exclusively", C: "A state's ability to issue its own currency and manage policy independently", D: "The elimination of all fiscal constraints" }, correct_answer: "C", explanation: "Paragraph B defines monetary sovereignty clearly." },
      { order_index: 3, type: "mcq", question_text: "Why do traditional transmission mechanisms weaken at the zero lower bound?", options: { A: "Interest rates become ineffective as a policy tool", B: "Governments stop spending entirely", C: "Inflation automatically rises", D: "Exchange rates stabilize completely" }, correct_answer: "A", explanation: "Paragraph C explains that low rates limit effectiveness." },
      { order_index: 4, type: "tfng", question_text: "The quantity theory of money assumes a stable relationship between money supply and prices.", options: null, correct_answer: "TRUE", explanation: "Paragraph A states this assumption explicitly." },
      { order_index: 5, type: "tfng", question_text: "All economists agree that monetary sovereignty eliminates economic risks.", options: null, correct_answer: "FALSE", explanation: "Paragraph B highlights criticisms and risks." },
      { order_index: 6, type: "tfng", question_text: "Quantitative easing is universally effective across all economies.", options: null, correct_answer: "FALSE", explanation: "Paragraph C notes its effectiveness is contested and uneven." },
      { order_index: 7, type: "matching", question_text: "Match paragraph C with its main idea", options: { A: "Definition of monetary sovereignty", B: "Limitations of policy transmission mechanisms", C: "Historical development of monetary theory", D: "Political role of central banks" }, correct_answer: "B", explanation: "Paragraph C focuses on transmission limitations." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Reevaluation of central banks within broader systems", B: "Interest rate theory", C: "Currency issuance mechanisms", D: "Inflation measurement techniques" }, correct_answer: "A", explanation: "Paragraph D discusses broader institutional context." },
    ],
  },
  {
    id: makeUUID("band80-sci-synthetic-biology"),
    topic: "science", difficulty: "band_80_plus", estimated_minutes: 9,
    passage_title: "Synthetic Biology and the Reconfiguration of Life",
    passage_text: "A. Synthetic biology represents a paradigmatic shift in the life sciences, moving beyond the descriptive ambitions of molecular biology toward an engineering-oriented approach to living systems. Rather than merely decoding genetic information, practitioners seek to design and construct novel biological functions through the systematic manipulation of genetic components. This transition reframes organisms not as fixed entities but as programmable substrates, amenable to modular assembly and iterative optimization.\n\nB. Central to this enterprise is the concept of standardization, whereby biological parts often referred to as biobricks are designed to function predictably across different contexts. This modular logic draws heavily from engineering disciplines, enabling the construction of increasingly complex genetic circuits. However, the analogy between biological and mechanical systems is imperfect: living organisms exhibit emergent properties and context-sensitive behaviors that resist full standardization, thereby complicating efforts to achieve reliable design.\n\nC. The promise of synthetic biology extends across diverse domains, from the production of biofuels and pharmaceuticals to the development of novel therapeutic strategies. Yet these applications are accompanied by profound ethical and ecological considerations. The release of engineered organisms into natural environments raises concerns about unintended consequences, including horizontal gene transfer and disruptions to existing ecosystems. Moreover, the capacity to redesign life at a fundamental level prompts questions about the moral boundaries of human intervention.\n\nD. These tensions highlight the dual character of synthetic biology as both a technological innovation and a site of philosophical inquiry. While its proponents emphasize efficiency, scalability, and problem-solving potential, critics caution against an uncritical embrace of its underlying assumptions. In particular, the reduction of life to a set of manipulable components risks overlooking the complexity and contingency inherent in biological systems. As the field continues to evolve, it necessitates not only technical refinement but also sustained reflection on the conceptual frameworks that guide its development.",
    tags: ["science"], created_by: "ai_generated", review_status: "pending",
    questions: [
      { order_index: 1, type: "mcq", question_text: "What is the central argument of the passage?", options: { A: "Synthetic biology is purely theoretical and has no practical applications", B: "Synthetic biology transforms biology into an engineering discipline but faces conceptual and ethical challenges", C: "All biological systems can be perfectly standardized like machines", D: "Synthetic biology eliminates ecological risks entirely" }, correct_answer: "B", explanation: "The passage highlights both the engineering shift and its limitations." },
      { order_index: 2, type: "mcq", question_text: "Why is the concept of 'biobricks' significant?", options: { A: "They eliminate genetic complexity", B: "They allow for predictable and modular design of biological systems", C: "They replace natural organisms entirely", D: "They prevent all emergent behaviors" }, correct_answer: "B", explanation: "Paragraph B explains standardization and modular design." },
      { order_index: 3, type: "mcq", question_text: "What is a key limitation of applying engineering principles to biology?", options: { A: "Biological systems lack genetic material", B: "Living organisms behave predictably in all contexts", C: "Emergent and context-dependent behaviors resist full standardization", D: "Engineering principles are irrelevant to science" }, correct_answer: "C", explanation: "Paragraph B highlights emergent properties and unpredictability." },
      { order_index: 4, type: "tfng", question_text: "Synthetic biology focuses only on understanding existing biological systems.", options: null, correct_answer: "FALSE", explanation: "Paragraph A states it involves designing new functions." },
      { order_index: 5, type: "tfng", question_text: "The release of engineered organisms poses no ecological risks.", options: null, correct_answer: "FALSE", explanation: "Paragraph C discusses ecological concerns." },
      { order_index: 6, type: "tfng", question_text: "The passage provides a definitive ethical framework for synthetic biology.", options: null, correct_answer: "NOT GIVEN", explanation: "Ethical issues are raised but not fully resolved." },
      { order_index: 7, type: "matching", question_text: "Match paragraph B with its main idea", options: { A: "Applications of synthetic biology", B: "Standardization and its limitations", C: "Ethical concerns", D: "Philosophical critique" }, correct_answer: "B", explanation: "Paragraph B discusses modular design and its limits." },
      { order_index: 8, type: "matching", question_text: "Match paragraph D with its main idea", options: { A: "Technical design principles", B: "Philosophical and conceptual implications", C: "Environmental risks", D: "Historical development" }, correct_answer: "B", explanation: "Paragraph D reflects on broader implications." },
    ],
  },
];

async function seed() {
  const client = await pool.connect();
  let inserted = 0;
  let skipped = 0;

  try {
    await client.query("BEGIN");

    for (const p of PASSAGES) {
      const existing = await client.query(
        "SELECT id FROM reading_passages WHERE passage_title = $1",
        [p.passage_title]
      );
      if (existing.rowCount > 0) {
        console.log(`\u23ED  "${p.passage_title}" already exists \u2014 skipping`);
        skipped++;
        continue;
      }

      await client.query(
        `INSERT INTO reading_passages (id, topic, difficulty, estimated_minutes, passage_title, passage_text, tags, created_by, review_status)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
        [p.id, p.topic, p.difficulty, p.estimated_minutes, p.passage_title, p.passage_text, p.tags, p.created_by, p.review_status]
      );

      for (const q of p.questions) {
        await client.query(
          `INSERT INTO reading_questions (passage_id, order_index, type, question_text, options, correct_answer, explanation)
           VALUES ($1, $2, $3, $4, $5, $6, $7)`,
          [p.id, q.order_index, q.type, q.question_text, q.options ? JSON.stringify(q.options) : null, q.correct_answer, q.explanation]
        );
      }

      console.log(`\u2714  Inserted "${p.passage_title}" (${p.questions.length} questions)`);
      inserted++;
    }

    await client.query("COMMIT");
    console.log(`\n\u2705 Band 8.0+ seed completed: ${inserted} inserted, ${skipped} skipped`);
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("\n\u2716  Seed failed \u2014 rolled back:", err.message);
    process.exit(1);
  } finally {
    client.release();
  }
}

seed()
  .then(() => pool.end())
  .catch((err) => { console.error("Fatal:", err.message); pool.end(); process.exit(1); });
